language: cpp
before_install:
- pip install --user cpp-coveralls
script:
- cmake -H. -B_build -DBUILD_TESTS=ON
- cmake --build _build
#- make && make check
#- ./configure --enable-gcov && make && make check
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'
